### ISSUE TITLE
ghpages/intro.md needs tweaking

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-parameter-registers#22]
ghpages/intro.md needs tweaking after the addition of the Flow attributes register (and more are coming!).
May be better not to list them all manually, perhaps just give some examples.
As the Parameter Registers have expanded in use, the phrasing of the What/How questions has also got a little dated.
Perhaps the content of master/README.md actually needs to move into docs/ and it could be used directly?

The fixed list at https://github.com/AMWA-TV/nmos-doc-build-scripts/blob/1923fd96bf65ad164d38c53908894a9c4937d078/make-indexes.sh#L60 is part of the same maintenance issue.

**Comment by garethsb-sony** [comment]
@peterbrightwell, maybe we ought to address this as part of the specs migration. I'll add it to the list!

**Comment by garethsb** [comment]
This repo is now sorted. I'm going through the other fixed lists.
