### ISSUE TITLE
Registers table should be for the current branch

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-parameter-registers#39]
At the moment, the table at e.g. https://specs.amwa.tv/nmos-parameter-registers/branches/publish-bcp-006/ links to `branches/main` rather than the current branch.

Presumably related to:

https://github.com/AMWA-TV/nmos-parameter-registers/blob/592de2d32075064d33b3efdabd58034a96d304f0/.render/_local/_includes/register_table.html#L12-L13

**Comment by peterbrightwell** [comment]
Yes, unfortunately the move to using `{% include register_table %}` doesn't play too well with the code in `make-indexes.sh` at the moment. Making this a relative link will break the table on the front page, so needs a bit more thought.

**Comment by peterbrightwell** [comment]
And more generally it would be good if the docs, APIs, schemas, examples menus for all the specs (which are generated by template includes) could be correct for the current branch/release.

**Comment by peterbrightwell** [comment]
Ok 4f8404b01d85a693eb71dff98425545918d5c0f7  and https://github.com/AMWA-TV/nmos-doc-build-scripts/commit/a01c4e4214f3551282e7766aa2a3eecb98ffb351 avoid broken/wrong links so closing.

The general case now is: https://github.com/AMWA-TV/nmos-doc-build-scripts/issues/49
